#!/usr/bin/env bash

set -e
git clone --recursive git@github.com:nihildeb/dotfiles.git $HOME/.dotfiles
echo ''
echo '* clone complete'

cd $HOME/.dotfiles
./script/bootstrap

# install bash_it
$HOME/.bash_it/install.sh

# update everything
$HOME/.bin/dotfiles_update

echo ''
echo '* init complete'

