#!/usr/bin/env bash

set -e
git clone --recursive git@github.com:nihildeb/dotfiles.git $HOME/.dotfiles
echo ''
echo '* clone complete'

cd $HOME/.dotfiles
./script/bootstrap

$HOME/.bin/dotfiles_update

echo ''
echo '* init complete'

