#!/usr/bin/env bash

set -e
echo '* updating dotfiles'

# update dotfiles
cd "$HOME/.dotfiles"
git pull
git submodule foreach git pull origin master
./script/bootstrap

# update bash
$HOME/.bash_it/install.sh

# update vim bundles
$EDITOR +BundleInstall +qall

echo '* updating dotfiles complete'
echo ' '
