#!/usr/bin/env bash

set -e
echo '* updating dotfiles'

# update dotfiles
cd "$HOME/.dotfiles"
git pull
git submodule foreach git pull origin master
./script/bootstrap

# update vim bundles
$EDITOR +BundleInstall +qall

source ~/.bash_profile

echo '* updating dotfiles complete'
echo ' '
