#!/usr/bin/env bash

set -e
echo '* updating dotfiles'

# update dotfiles
cd "$HOME/.dotfiles"
git pull --recursive
./script/bootstrap

# update bash
$HOME/.bash-it/install.sh

# update vim bundles
$EDITOR +BundleInstall +qall

echo '* updating dotfiles complete'
echo ' '
