#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  echo " ruby -e \"$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)\""
  exit
fi

# Install homebrew packages
brew install grc coreutils spark hub node

exit 0
